### ISSUE TITLE
Two swarm clusters - Unable to find a node that satisfies the following conditions

### ISSUE THREAD

**Issue by noose** [docker/classicswarm#2269]
Hi!
I've created 2 swarm nodes with 2 managers, then I tried to create 2 containers with nginx.

``` yml
# docker-compose.yml
interlock:
#    image: ehazlett/interlock:master
    build: interlock # I passed some config inside - doesn't matter 
    command: "-D run --discovery consul://consul.local:8500/"
    ports:
        - 8080:8080

nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
        - 80:80
    labels:
        - "interlock.ext.name=nginx"
    links:
        - interlock:interlock
```

``` bash
docker-compose up -d
```

Everything is ok. But when I run:

``` bash
% docker-compose scale nginx=2

WARNING: The "nginx" service specifies a port on the host. If multiple containers for this service are created on a single host, the port will clash.
Creating and starting interlock_nginx_2 ... error

ERROR: for interlock_nginx_2  Unable to find a node that satisfies the following conditions
[port 80 (Bridge mode)]
[available container slots]
[--link=interlock_interlock_1:interlock --link=interlock_interlock_1:interlock_1 --link=interlock_interlock_1:interlock_interlock_1]
```

I belive that in my case swarm should find node with free ports (80 in my case) and create nginx on that node.

``` bash
% docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                               NAMES
91e88283fa00        nginx:latest          "nginx -g 'daemon off"   10 minutes ago      Up 10 minutes       10.0.1.207:80->80/tcp, 443/tcp      ip-10-0-1-207/interlock_nginx_1
edeca7930c4d        interlock_interlock   "/bin/interlock -D ru"   10 minutes ago      Up 10 minutes       80/tcp, 10.0.1.207:8080->8080/tcp   ip-10-0-1-207/interlock_interlock_1,ip-10-0-1-207/interlock_nginx_1/interlock,ip-10-0-1-207/interlock_nginx_1/interlock_1,ip-10-0-1-207/interlock_nginx_1/interlock_interlock_1
```

``` bash
% docker info
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 44
Server Version: swarm/1.2.2
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 2
 ip-10-0-1-206: 10.0.1.206:2376
  └ ID: 35GV:JUQF:KSKM:U2RE:4DLD:5SCA:6LKK:IRB6:5ZTN:XWQV:T3R4:2E7T
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 8.187 GiB
  └ Labels: executiondriver=, kernelversion=3.13.0-74-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=devicemapper
  └ Error: (none)
  └ UpdatedAt: 2016-05-24T16:08:20Z
  └ ServerVersion: 1.11.1
 ip-10-0-1-207: 10.0.1.207:2376
  └ ID: ZML2:L26T:7EO2:2FDE:GYXY:AH2K:7SEO:DEHF:563I:F6MT:DKFG:OVGN
  └ Status: Healthy
  └ Containers: 3
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 8.187 GiB
  └ Labels: executiondriver=, kernelversion=3.13.0-74-generic, operatingsystem=Ubuntu 14.04.3 LTS, storagedriver=devicemapper
  └ Error: (none)
  └ UpdatedAt: 2016-05-24T16:08:09Z
  └ ServerVersion: 1.11.1
Plugins:
 Volume:
 Network:
Kernel Version: 3.13.0-74-generic
Operating System: linux
Architecture: amd64
CPUs: 4
Total Memory: 16.37 GiB
Name: 92d794192bb0
Docker Root Dir:
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support
```
