### ISSUE TITLE
Swarm rescheduling compose app with `depends_on`

### ISSUE THREAD

**Issue by wallnerryan** [docker/classicswarm#2360]
Version

```
$:-> docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      ucp/1.1.1
 API version:  1.22
 Go version:   go1.6.2
 Git commit:   f28e3be
 Built:        Fri May 27 17:25:03 UTC 2016
 OS/Arch:      linux/amd64
```

Info

```
$:-> docker info
Containers: 18
 Running: 15
 Paused: 0
 Stopped: 3
Images: 36
Server Version: swarm/1.2.3
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 3
 mha-aws-consul: 172.20.0.110:12376
  └ ID: OOHF:LQ3Y:WLRD:OWJT:QNWP:MCSO:5HUO:EU5O:AG22:ILZE:BAGQ:3IGM
  └ Status: Healthy
  └ Containers: 11
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 7.67 GiB
  └ Labels: executiondriver=, kernelversion=3.13.0-74-generic, operatingsystem=Ubuntu 14.04.3 LTS, provider=amazonec2, storagedriver=aufs
  └ UpdatedAt: 2016-06-17T16:31:53Z
  └ ServerVersion: 1.11.2
 mha-aws-demo0: 172.20.0.249:12376
  └ ID: HMKN:COXW:E2EF:4JEC:56XU:VKWA:O74T:N6RZ:PZSX:FT66:GH34:IRWD
  └ Status: Healthy
  └ Containers: 3
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 7.67 GiB
  └ Labels: executiondriver=, kernelversion=3.13.0-74-generic, operatingsystem=Ubuntu 14.04.3 LTS, provider=amazonec2, storagedriver=aufs
  └ UpdatedAt: 2016-06-17T16:32:01Z
  └ ServerVersion: 1.11.2
 mha-aws-demo1: 172.20.0.43:12376
  └ ID: OCGO:A5VH:VATD:JVLO:5YDM:QAXQ:QEPF:HAXD:L7KK:L6IH:U2CQ:OIER
  └ Status: Healthy
  └ Containers: 4
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 7.67 GiB
  └ Labels: executiondriver=, kernelversion=3.13.0-74-generic, operatingsystem=Ubuntu 14.04.3 LTS, provider=amazonec2, storagedriver=aufs
  └ UpdatedAt: 2016-06-17T16:32:18Z
  └ ServerVersion: 1.11.2
Cluster Managers: 1
 172.20.0.110: Healthy
  └ Orca Controller: https://172.20.0.110:443
  └ Swarm Manager: tcp://172.20.0.110:23766
  └ KV: etcd://172.20.0.110:12379
Plugins:
 Volume:
 Network:
Kernel Version: 3.13.0-74-generic
Operating System: linux
Architecture: amd64
CPUs: 6
Total Memory: 23.01 GiB
Name: ucp-controller-mha-aws-consul
ID: GMGV:UDTK:B53J:MSZH:FZXB:ZYNH:5GAN:GHOM:AML7:JSPL:P5WD:ILKI
Docker Root Dir:
Debug mode (client): false
Debug mode (server): false
WARNING: No kernel memory limit support
```

I have a compose application that looks like this

```
version: '2'
volumes:
  demononet:
    driver: flocker
services:
  web:
    image: clusterhq/moby-counter:dcsea
    environment:
       - "USE_REDIS_HOST=redis"
       - "affinity:container==apps_redis_1"
       - "reschedule:on-node-failure"
    links:
      - redis
    ports:
      - "80:80"
    restart: always
    depends_on:
      - redis
  redis:
    image: redis:latest
    environment:
       - "constraint:node!=mha-aws-demo0"
       - "reschedule:on-node-failure"
    volumes:
       - 'demononet:/data'
```

The Web application "moby-counter" depends on redis, both have `"reschedule:on-node-failure"` in the environment.

When I fail a node to test this, i see that the swarm manager seems to not take into account that the `depends_on` should also apply to rescheduling. I would expect for swarm to reschedule in order if they are related via dependencies.

```
time="2016-06-17T16:23:07Z" level=info msg="Removed Engine mha-aws-demo2"
time="2016-06-17T16:23:07Z" level=error msg="Failed to reschedule container ee9be0267fa07f5bdb3593d2d1caee4f9f0eef5ed23f5933b7d75a78f9027738: Unable to find a node that satisfies the following conditions \n[port 80 (Bridge mode)]\n[available container slots]\n[container==apps_redis_1 (soft=false)]"
time="2016-06-17T16:23:18Z" level=info msg="Rescheduled container 36c2f9b5c2ecd67595664a9f50a25c2e93206727d4ef631a0c2baac968a26b2e from mha-aws-demo2 to mha-aws-demo1 as 2ce3ce99ff20612b0ac667f407731f3e91fdec6b38708e4b86513d5872b4ed6e"
time="2016-06-17T16:23:18Z" level=info msg="Container 36c2f9b5c2ecd67595664a9f50a25c2e93206727d4ef631a0c2baac968a26b2e was running, starting container 2ce3ce99ff20612b0ac667f407731f3e91fdec6b38708e4b86513d5872b4ed6e"
```
