### ISSUE TITLE
Connect to a docker swarm master with windows docker-machine

### ISSUE THREAD

**Issue by charliemaiors** [docker/classicswarm#2477]
Hi all,

how I can connect to a docker swarm on multiple raspberry pi using windows docker client (or docker-machine)? using -H option the docker daemon on swarm master refuses connection. Using docker-machine create  with generic driver the provisioner fails because it can't detect target OS. I'm using plain raspbian (lite version, without  desktop environment) and docker-engine installed from get.docker.com. Thanks in advance.

Best Regards

**Comment by westsouthnight** [comment]
@charliemaiors If i right understand your its not a problem.
as example
i have 
```
stand-1-test-1.example.com
stand-1-test-2.example.com
stand-1-test-3.example.com
stand-1-test-4.example.com (Swarm Master) 
```
![screen_shot_2016-09-08_at_18_21_08](https://cloud.githubusercontent.com/assets/17825649/18355276/4a2c021a-75f1-11e6-86e4-6469ddba6be7.png)
![screen_shot_2016-09-08_at_18_19_45](https://cloud.githubusercontent.com/assets/17825649/18355277/4a2e07fe-75f1-11e6-9370-7678a4a608d5.png)

And can (if on swarm master opened swarm manager port) from any windows machine with docker-machine (latest docker for windows) do:

docker -H stand-1-test-4.example.com:4000 ps

**Comment by westsouthnight** [comment]
@charliemaiors 

PS: docker-machine works like simple linux vm with docker-engine on board, and you from windows cmd/gitbash/powershell can use standard command like you run on other linux hosts:

``` docker -H stand-1-test-4.example.com:4000 ps ```

**Comment by charliemaiors** [comment]
@westsouthnight I've this situation

![docker](https://cloud.githubusercontent.com/assets/4567810/18360280/ac415584-75fd-11e6-9f7d-3e7dc6a00509.png)

I've created the swarm running ```docker swarm init```  on dockermaster and ```docker swarm join``` (with options retrieved using ```docker swarm token-join``` on master) on each node, I've also deployed a ping service just for testing. When I ran this command on windows powershell (with latest docker toolbox), the machine refuse the connection

``` bash
PS C:\Users\maior> docker -H 192.168.1.11:4000 ps
An error occurred trying to connect: Get http://192.168.1.11:4000/v1.24/containers/json: dial tcp 192.168.1.11:4000: connectex: No connection could be made because the target machine actively refused ```

**Comment by westsouthnight** [comment]
@charliemaiors you need to check your fw and opened ports on dockermaster

please give your out from commands: ``` netstat -tap | grep 4000 ``` & ``` ufw status | grep 4000 ``` or ``` iptables -L | grep 4000 ```

![screen shot 2016-09-09 at 12 46 29](https://cloud.githubusercontent.com/assets/17825649/18382889/a2a16364-768b-11e6-9686-32e22a0243f0.png)

**Comment by charliemaiors** [comment]
@westsouthnight  iptables is not configured (everything is allowed), this is the output

![result](https://cloud.githubusercontent.com/assets/4567810/18383182/9e6e6f00-7684-11e6-813f-1ae626d91dd1.png)

**Comment by westsouthnight** [comment]
@charliemaiors what in output if you run ``` netstat -tap | grep 4000 ```? Sever listen on swarm-manager port?

**Comment by westsouthnight** [comment]
@charliemaiors and please show your ``` docker ps -a ``` from swarm manager

**Comment by charliemaiors** [comment]
`netstat -tap | grep 4000` result: 

![res](https://cloud.githubusercontent.com/assets/4567810/18384425/af3fc13e-768a-11e6-80ca-fbe7aac7923c.png)

seems that swrm manager protocol is not working, but the `netstat -tap` shows: 

![res2](https://cloud.githubusercontent.com/assets/4567810/18384491/18ed3d00-768b-11e6-820f-cf9fd194a5e2.png)

and `docker ps -a` on swarm master shows this output:

![res1](https://cloud.githubusercontent.com/assets/4567810/18384513/343098be-768b-11e6-948d-f687f1d8f172.png)

but the swarm seems to be active and ready

**Comment by westsouthnight** [comment]
@charliemaiors try to run ``` docker -H 192.168.1.11:2377 ps ```

**Comment by westsouthnight** [comment]
@charliemaiors and, i see something else - looks like your swarm-manager bind'ed to localhost (127.0.0.1) and cannot to be discovered from network. I think you need to do deploy swarm cluster like in swarm production [manual ](https://docs.docker.com/swarm/multi-manager-setup/), and use for swarm-cli & swarm-manager docker containers

my ansible part:

```

- name: Create a Swarm-Master docker container 
  become: true
  docker_container:
      name: swarm-{{ swarm_node_type }}
      image: swarm
      command: manage -H :2375 --replication --advertise "{{ ansible_default_ipv4['address'] | join }}":4000 consul://"{{ ansible_default_ipv4['address'] | join }}":8500
      ports:
        - "4000:2375"
      volumes:
        - "/etc/hosts:/etc/hosts"
      restart_policy: unless-stopped
      detach: True
      recreate: yes 
      state: started
      docker_url: tcp://0.0.0.0:2375
  when: swarm_node_type == "master"

- name: Create a Swarm-Cli docker container
  docker_container:
      name: swarm-cli-{{ swarm_node_type }}
      image: swarm
      command: join --addr="{{ ansible_default_ipv4['address'] | join }}":2375 consul://"{{ ansible_default_ipv4['address'] | join }}":8500 
      restart_policy: unless-stopped
      volumes:
        - "/etc/hosts:/etc/hosts"
      detach: True
      recreate: yes 
      state: started
      docker_url: tcp://0.0.0.0:2375

```
