### ISSUE TITLE
Cannot create container for service nc: Unable to find a node that satisfies the following conditions

### ISSUE THREAD

**Issue by viveky4d4v** [docker/classicswarm#2536]
Docker machine setup -

```
$ docker-machine ls
NAME     ACTIVE      DRIVER    STATE     URL                        SWARM          DOCKER    ERRORS
consul   -           generic   Running   tcp://192.168.99.94:2376                  v1.12.2   
sm1      -           generic   Running   tcp://192.168.99.91:2376   sm5 (master)   v1.12.2   
sm2      -           generic   Running   tcp://192.168.99.92:2376   sm5 (master)   v1.12.2   
sm3      -           generic   Running   tcp://192.168.99.93:2376   sm5 (master)   v1.12.2   
sm4      -           generic   Running   tcp://192.168.99.95:2376   sm5 (master)   v1.12.3   
sm5      * (swarm)   generic   Running   tcp://192.168.99.96:2376   sm5 (master)   v1.12.3   
```

Setting the environment to master machine - 

```
 eval $(docker-machine env --swarm sm5)
```

Overlay network - 

```
 $ docker network ls 
 NETWORK ID          NAME                  DRIVER              SCOPE
 0db485a060f9        cheerios              overlay             global              
 48c0268d5393        db/bridge             bridge              local               
 1e022cc8c0e7        db/docker_gwbridge    bridge              local               
 659a7a4d85a7        db/host               host                local               
 f09560861ed8        db/none               null                local               
 6fb3c8779fdb        nc/bridge             bridge              local               
 50544f7796d7        nc/host               host                local               
 79b2f0d4d548        nc/none               null                local               
 54c037aa64d4        nc1/bridge            bridge              local               
 cb614bd91dd1        nc1/host              host                local               
 db46fdf10721        nc1/none              null                local               
 b1e2e123d2c5        wd/bridge             bridge              local               
 459edee88b77        wd/docker_gwbridge    bridge              local               
 c83be7e1b8b5        wd/host               host                local               
 d417ee893a2c        wd/none               null                local               
 31f4d58e34b7        web/bridge            bridge              local               
 b06e1704b0de        web/docker_gwbridge   bridge              local               
 b0b566aa617d        web/host              host                local               
 16b609f89d28        web/none              null                local               
```

Compose file - 

```
version: "2" # https://docs.docker.com/compose/compose-file/

services:
    nc:
      image: vivekh/nc:v1
      environment:
         - "constraint:node==sm4"
      ports:
         - 80:80
      command: "/usr/sbin/nginx"

     nc1:
         image: vivekh/nc:v1
         environment:
             - "constraint:node==sm5"
         ports:
            - 80:80
         command: "/usr/sbin/nginx"

    networks:
      default:
          external:
            name: cheerios
```

Error while bringing the stack up - 

```
     ERROR: for nc1  Cannot create container for service nc1: Unable to find a node that satisfies the                following conditions 
      [port 80 (Bridge mode)]
      [ available container slots]
      [node==sm5]

     ERROR: for nc  Cannot create container for service nc: Unable to find a node that satisfies the following conditions 
     [port 80 (Bridge mode)]
      [available container slots]
     [node==sm4]
     ERROR: compose.cli.main.main: Encountered errors while bringing up the project.
```

I can confirm that nothing is running on port 80 on any of the machines "nc" & "nc1"  . It doesn't look like a port mapping issue to me because i tried with different ports as well . 

I believe i am not able to use "constraint:node==xxxx" because whenever i use it i get the error else everything works fine .  Not really sure what i am really missing . I am fairly new to docker swarm . Please suggest .

I followed below doc to setup - 

https://docs.docker.com/compose/swarm/
