### ISSUE TITLE
Can't deploy application to swarm using docker-compose after upgrading to docker 1.13

### ISSUE THREAD

**Issue by zoheb-nawaz** [docker/classicswarm#2694]
I'm trying to deploy an application to a swarm cluster (CLASSIC standalone swarm and not the one that comes bundled with docker-engine) using docker-compose (v 1.11.2).

Please find below usual information:

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Now, the docker daemon was  configured in **/etc/systemd/system/docker.service.d/tls.conf** as follows for docker version 1.11 : 

```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -D --selinux-enabled --tls=true --tlsverify=true --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server-cert.pem --tlskey=/etc/docker/server-key.pem -H=0.0.0.0:2376 --cluster-store="consul://consul:8500" --cluster-advertise="eth0:2376"

```
The services are defined in a docker-compose.yml file. In the previous version (1.11), we deployed the app as follows: 

`docker-compose -H <MANAGER-IP>:2376 up -d`

However, since upgrading to docker 1.13, configuring the daemon as before prevents docker daemon from starting. Docker status produces the following : 

`"Error starting daemon: discovery advertise parsing failed (invalid cluster advertise IP address or interface name ("eth0:2376") : route ip+net : no such network interface)"
`
On changing tls configuration to :

```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -D --selinux-enabled --tls=true --tlsverify=true --tlscacert=/etc/docker/ca.pem --tlscert=/etc/docker/server-cert.pem --tlskey=/etc/docker/server-key.pem -H=0.0.0.0:2376 
```

I am able to start the docker service. Now to configure the consul store and advertise the cluster, I run the following on the swarm manager : 

`docker run -d -p 3376:3376 -v ~/.docker:/certs:Z swarm manage -H :3376 --tlsverify --tlscacert=/certs/ca.pem --tlscert=/certs/cert.pem --tlskey=/certs/key.pem --replication --advertise $(hostname):2376 consul://consul:8500`

This sets-up the cluster. I verified the working of the cluster using the hello-world container.

However, to deploy our application, we tried to do follows again : 

`docker-compose -H <MANAGER-IP>:3376 up -d`

This presents the following error : 

`**ERROR: Error response from daemon: datastore for scope "global" is not initialized**`

It seems like as the daemon has been configured differently, the app isn't getting deployed. 

How do I get it working with docker 1.13? Is there a different way to configure docker daemon with --cluster-advertise and --consul-store in case of docker 1.13?

**Comment by nishanttotla** [comment]
@zoheb-nawaz what does your compose file look like?

**Comment by zoheb-nawaz** [comment]
@nishanttotla The docker-compose.yml file is as below : 

```
version: "3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
  vote:
    image: dockersamples/examplevotingapp_vote:after
    ports:
      - 5000:80
    networks:
      - frontend
    depends_on:
      - redis
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
  result:
    image: dockersamples/examplevotingapp_result:after
    ports:
      - 12000:80
    networks:
      - backend
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=VOTING]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "7777:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
  backend:

volumes:
```
