### ISSUE TITLE
Container affinity for bridge network not working?

### ISSUE THREAD

**Issue by bergtwvd** [docker/classicswarm#2799]
On a 5-node Docker cluster we have Docker swarm (standalone, swarm version 1.2.7 (2005aec)) on node 1 running, pointing to the other four nodes 2..5.

We use the following compose file to create the network infrastructure:

````
version: '2'

services:
 placeholder:
  image: busybox
  networks:
  - training
  - disnet

networks:
 training:
  driver: overlay
  ipam:
   config:
   - subnet: 10.12.0.0/24
     gateway: 10.12.0.1
 disnet:
  driver: bridge
````

We run the above composition in advance since the creation of the overlay network takes some time.

Next, we start a composition with a set of containers. Two of the containers in the composition need to be attached to the bridge network ``disnet`` created earlier. These two containers use broadcast to communicate (hence the use of a bridge here). A snippet of the composition is shown below:

````
version: '2'

services:
 C1:
  image: <container image>
  networks:
  - training
  - disnet

 C2:
  image: <container image>
  networks:
  - disnet

...
````

We do not know on which node the bridge network is created in the cluster, and expect that swarm will ensure that both C1 and C2 will be scheduled together on the node with the bridge.

However, this seems not always to be the case.

Is this correct?

And is there an alternate way to make this happen (affinity, ...)?
