### ISSUE TITLE
Not able to set different CPU usage limit for service on different nodes in Docker Swarm?

### ISSUE THREAD

**Issue by bsalunke** [docker/classicswarm#2886]
I'm trying to set the CPU usage limit for the service in the docker swarm cluster. 
Using following config **limits: ->  cpus: '0.50'** in the docker swarm yaml file to set the limit for CPU usage for a particular service.

```
version: '3.3'
services:
  My-Service:
    image: my-regisrty/myiamge:latest
    deploy:
      mode: global  # Deploy 1 container on each node == DaemonSet
      resources:
        limits:
          cpus: '0.50'

```
This set the My_Service CPU usage limit to 50% on all the nodes.
However I wanted to set different CPU usage limit on different swarm nodes.

Is there any option to set node specific CPU usage limit whiling deploying the service on swarm cluster?
