### ISSUE TITLE
Cannot deploy an image by its ID to a swarm

### ISSUE THREAD

**Issue by twhittakeriq** [docker/classicswarm#2937]
I created a docker-compose.yml file that references docker images by ID. When I try to deploy the compose file to a swarm, I get the error "No such image: 2e69080faee3:latest" repeatedly. 
 The image does exist locally. In my scenario, it was loaded from a tar file that was provided to me by an upstream process.

Here is the docker-compose.yml:
```
version: '3.4'
services:
  registry:
    image: 2e69080faee3
```
This image *does* exist on the swarm only node attached to the swarm (the manager node in this case).
